// module.exports={
//   development:{
//     client:"pg",
//     connection:{
//       host:"localhost",
//       database:"postgres"
//     },
//     migrations:{
//       directory:__dirname+"/db/migrations"
//     },
//     seeds:{
//       directory:__dirname+"/db/seeds",
//     }
//   },
//   production:{
//     client:"pg",
//     connection:process.env.url,
//      migrations:{
//       directory:__dirname+"/db/migrations"
//     },
//     seeds:{
//       directory:__dirname+"/db/production",
//     }
//   }
// }